# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Sync Gitee

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Sync code to Gitee  #把主分支的代码强制同步到Gitee
      run: |
            git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_PASSWORD }}@gitee.com/liangyuanpeng/liangyuanpeng.git
            git fetch --unshallow origin
            git push gitee main:master -f
